- server/services/completion.py
- server/services/context.py
- server/services/language.py
- server/services/xsd/parser.py
- server/services/xsd/types.py
- server/tests/unit/test_completion.py
- server/tests/unit/test_context.py
- server/types.py
The previous tag location using a basic string finding solution has been replaced by a SAX parser with tolerance to XML syntax errors.
This new solution provides much more information about the context, i.e. in addition to the current node definition, it provides information about the type of the token under the cursor and the complete node path.
This PR also contains test cases for the new classes and some minor code cleanup.
> Improve context information at cursor position

- server/services/completion.py
- server/services/context.py
- server/tests/unit/test_context.py
Some improvements to determine if the cursor is inside an attribute definition or within the content part of a tag. With this information, we can avoid triggering the auto-completion in the wrong places.
Added more tests to check the context information is as expected.
> Fixes #3 by using more information about the context

- server/services/context.py
- server/services/xsd/types.py
- server/tests/unit/test_context.py
- server/tests/unit/test_xsd_parser.py
* Added a [function](https://github.com/davelopez/galaxy-tools-extension/compare/fix-contex-node?expand=1#diff-81db3ec65dc6328bb030ccf2859f5bfcR125-R144) to resolve the node definition (XSD) using the current path of node names.
* Fixed how the [node stack is calculated](https://github.com/davelopez/galaxy-tools-extension/compare/fix-contex-node?expand=1#diff-fc334655ded569ca2404b0b758a8d677R268-R296) when the XML is broken or incomplete.
* Added some tests for edge cases.
> Fixes #16 by resolving the correct node definition

- server/services/context.py
- server/services/language.py
- server/services/xsd/service.py
- server/services/xsd/types.py
- server/tests/unit/test_context.py
- setup.cfg
The documentation retrieval on hover has been improved by using the token information from the context.
- The documentation is now provided for tags and attributes (previously only tags where supported).
- The ``XmlContext.token_range`` has been included to highlight the position of the context token.
- The correct XSD element definition is now associated with the token so the correct documentation is shown (if available).
Included more tests for this functionality.
Closes #8
> Improve hover help

- README.md
- client/src/commands.ts
- client/src/extension.ts
- client/src/tagClosing.ts
- docs/CHANGELOG.md
- server/features.py
- server/server.py
- server/services/completion.py
- server/services/context.py
- server/services/language.py
- server/tests/unit/test_completion.py
- server/tests/unit/test_context.py
- server/types.py
Implementation of the auto-close tag feature.
The client (Node.js) implementation is based on [this solution](https://github.com/redhat-developer/vscode-xml/blob/master/src/tagClosing.ts) originally from Microsoft HMTL language-features.
Closes #11
> Autoclose tags feature

- client/src/snippets.json
- package.json
Configured the VSCode extension to contribute snippets defined in [snippets.json](https://github.com/davelopez/galaxy-tools-extension/compare/snippets?expand=1#diff-663e38ec260b17239e542bd620f28f2e) file.
The ``gtool`` snippet creates the basic structure of a Galaxy Tool.
More snippets can be contributed to this file following the snippets syntax [here](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax)
> Add first snippet to create a basic tool template

- server/services/completion.py
- server/services/context.py
- server/services/language.py
- server/tests/unit/test_completion.py
- server/tests/unit/test_xsd_parser.py
When an attribute defined in the XSD contains enumeration restrictions, the values of the enumeration are used to auto-complete the attribute.
Right now you can trigger the value auto-completion when the cursor is inside the attribute value and you invoke the completion command by pressing ``ctrl+space``.
> Autocomplete attribute values with enumeration restrictions

- server/services/context.py
- server/tests/unit/test_context.py
When the cursor was positioned on an opening or closing CDATA block, the context parser should stop and classify the context as ``content``. Before this fix, the parser will skip the CDATA annotation and continue parsing beyond the target position. This could result in invalid node stacks resolution when the context is positioned exactly over these CDATA elements.
To detect when the cursor is on the CDATA block, [these methods](https://github.com/davelopez/galaxy-tools-extension/compare/fix-cdata-context?expand=1#diff-fc334655ded569ca2404b0b758a8d677R247-R255) were added. The rest of the _empty_ methods must be declared to implement the LexicalHandler for SAX defined [here](https://github.com/davelopez/galaxy-tools-extension/compare/fix-cdata-context?expand=1#diff-fc334655ded569ca2404b0b75 …
> Fix CDATA context

- server/services/completion.py
- server/services/context.py
- server/tests/unit/test_completion.py
- server/tests/unit/test_context.py
When trying to auto-close a tag in the middle of a file where there is a tag mismatch, the context was invalid and the auto-completion failed.
This PR adds the ``mismatched tag`` case to the supported recovery exceptions.
> Fix auto-close when tag mistmatched

- server/services/completion.py
- server/services/context.py
- server/tests/unit/test_completion.py
- server/tests/unit/test_context.py
This PR closes #26 by introducing the following improvements during attribute auto-completion:
- The attributes are now displayed in the same order as they are defined in the XSD instead of alphabetical order.
- If an attribute is already defined in the document, this attribute is no longer suggested by the auto-completion.
Some tests added for this functionality.
> Improve attribute completion

- server/services/completion.py
- server/services/context.py
- server/tests/unit/test_context.py
There was an unwanted behaviour when typing a space inside a closing or self-closing tag that would trigger the current node attribute autocompletion.
This PR fixes this bug detecting when the context is inside a closing tag and, in that case, ignoring the attribute completion.
> Fix completion on closing tag

- server/services/completion.py
- server/services/xsd/parser.py
- server/tests/unit/test_xsd_parser.py
As defined in #29, this PR displays the suggested tags in the same order that they appear in the [Galaxy.xsd](https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/tool_util/xsd/galaxy.xsd) instead of the default alphabetical order. This helps to maintain the recommended order of tags as in the [Galaxy IUC Coding Style](https://galaxy-iuc-standards.readthedocs.io/en/latest/best_practices/tool_xml.html?#coding-style) without the need to maintain an additional list just for the ordering. Currently, the XSD should be updated in a future version to declare the elements in the same order described in the guidelines.
> Improve tag ordering on suggestions

- server/CHANGELOG.md
- server/galaxyls/services/completion.py
- server/galaxyls/services/xsd/service.py
- server/galaxyls/services/xsd/types.py
- server/galaxyls/tests/unit/test_completion.py
- server/galaxyls/tests/unit/test_xsd_parser.py
- server/galaxyls/tests/unit/test_xsd_service.py
The ``<expand>`` element for macros is now better supported:
- This element is defined directly in the [XsdTree](https://github.com/davelopez/galaxy-language-server/compare/support-expand-element?expand=1#diff-2a462b2b25c733314371cb45981f8e26f25b5fe68cfb3793c14142ec56c47c3dR104) since it can not be added to the XSD schema itself.
- The ``expand`` tag will be now displayed in the auto-completion list of every element.
- The error when hovering the ``<expand>`` element has been fixed #41.
> Support expand element - Fixes #41

- client/CHANGELOG.md
- client/src/setup.ts
In version 0.1.1 of the extension. there was a trailing double-quotes character left in one of the commands for the language server installation.
This doesn't seem to affect the installation on Windows but was breaking the installation on Unix systems 😅 
This PR fixes #48
> Fix bug installing language server on Unix

- client/.eslintrc.json
- client/src/extension.ts
In the current version, when we press `enter` inside an element, we have to manually indent the next element:
This PR configures the indentation rules of the language to allow auto-indent:
Also, some minor refactorings and code documentation was added.
> Feature auto indent

- client/CHANGELOG.md
- client/README.md
- client/package.json
- client/src/extension.ts
- server/CHANGELOG.md
- server/galaxyls/config.py
- server/galaxyls/server.py
- server/galaxyls/services/completion.py
- server/galaxyls/services/language.py
- server/galaxyls/tests/unit/test_completion.py
- server/galaxyls/tests/unit/test_config.py
The language server now loads the client configuration when it is initialized and uses the settings to control some of the features.
In particular, two settings have been added to the extension to control the auto-completion feature.
Closes #54
> Add configuration parameters

- .github/workflows/release.yml
- client/CHANGELOG.md
- client/package.json
- server/CHANGELOG.md
- server/requirements.txt
This PR adds some small changes in preparation for the release:
- Updated changelogs.
- Updated the extension's manifest to reference the new repository URL.
- Fixed link in release template.
- Updated dependency `galaxy-tool-util` to 20.9.1
> Prepare release 0.2.0

- server/galaxyls/services/completion.py
- server/galaxyls/services/context.py
- server/galaxyls/tests/unit/test_completion.py
This closes #29 by using the capabilities of the new parser to check if a tag has reached the maximum number of occurrences so it won't be suggested anymore.
Additionally, some tests and small fixes were added.
> Improve completion

- .vscode/launch.json
- server/galaxyls/services/xsd/parser.py
- server/galaxyls/services/xsd/types.py
- server/galaxyls/tests/unit/test_xsd_service.py
This PR fixes #63 by retrieving the documentation annotation from the XSD type definition when there is no direct annotation on the element itself. Now, most of the elements should show the correct documentation on hover.
Some of the type hints were consolidated across the related files.
Also, a couple of tests for this fix were added.
> Fix xsd documentation hover

- client/README.md
- client/src/extension.ts
- client/src/setup.ts
This makes the installation process more transparent to the user when the VSCode extension is activated for the first time.
Now, instead of directly prompt the user for the Python binary, it shows a notification indicating that the language server package needs to be installed and the user can read more about the installation using the `More Info` button (link to the readme).
During installation, if the required Python version is detected automatically, the virtual environment will be created and the package installed. If the required version can not be found, another notification will be presented to the user to manually select the correct version in the system.
This closes #59
> Improve installation feedback

- server/galaxyls/services/xml/scanner.py
- server/galaxyls/tests/unit/test_context.py
The state of the scanner was not being properly updated when an XML comment was found. This was breaking the parser when there was more than one XML comment in the file.
This should fix #69
> Fix incorrect scanner state after comment

- server/galaxyls/server.py
- server/galaxyls/services/context.py
- server/galaxyls/services/language.py
- server/galaxyls/services/xml/document.py
- server/galaxyls/services/xml/nodes.py
- server/galaxyls/services/xsd/service.py
- server/galaxyls/services/xsd/validation.py
- server/galaxyls/tests/unit/test_context.py
- server/galaxyls/tests/unit/test_validation.py
- server/galaxyls/tests/unit/utils.py
- server/galaxyls/tests/unit/xml/test_parser.py
- server/requirements-dev.txt
This PR detects the type of XML document when a request is received by the server and, if the XML is not one of the supported types (`tool` and `macros` at the moment), further processing of the request is ignored. This fixes some false positives when you are working with different kinds of XML documents and the Galaxy Language Server is installed since the server will not try to validate (or use any other galaxy tool-related feature) those files.
Some refactoring was needed to simplify and unify the way XML documents are processed by some of the services. Also, additional tests were added.
This fixes #74
> Avoid processing unknown XML documents

- client/package.json
- client/src/constants.ts
- client/src/extension.ts
- client/src/languages/cheetah.language-configuration.json
- client/src/languages/galaxytoolxml.language-configuration.json
- client/src/languages/restructuredtext.language-configuration.json
- client/src/syntaxes/cheetah.tmLanguage.json
- client/src/syntaxes/galaxytoolxml.tmLanguage.json
- client/src/syntaxes/restructuredtext.tmLanguage.json
- client/src/syntaxes/token.injection.json
Instead of using the default language configuration and grammar for plain old XML files in Galaxy tool wrappers, a new `galaxytool` (any suggestions for a better name?) [language identifier](https://github.com/galaxyproject/galaxy-language-server/compare/syntax-highlight?expand=1#diff-1846122c2c83a486a3693f7966aa522c34cf489f674185c4da0d9221683fd81fR34) has been defined along with new [grammar](https://github.com/galaxyproject/galaxy-language-server/compare/syntax-highlight?expand=1#diff-a5edc587c0e6c95988c31502d478ebdf67ba2f76ad63db3a2fa7d8786cc1ed65) and [configuration](https://github.com/galaxyproject/galaxy-language-server/compare/syntax-highlight?expand=1#diff-9de90a0c1e88d491eadcaad87d1d63a43ec9db925f8e712e09be84682596c1c2) files based on the existing one …
> Basic embedded language syntax highlighting

- README.md
- server/galaxyls/services/tools/document.py
- server/galaxyls/services/tools/generators/command.py
- server/galaxyls/services/tools/generators/snippets.py
- server/galaxyls/services/tools/generators/tests.py
- server/galaxyls/services/xml/document.py
- server/galaxyls/services/xml/nodes.py
- server/galaxyls/tests/unit/test_tools.py
This PR fixes #82 by using the `unexpanded` tool document to calculate the insert position inside the document.
An improvement for the auto-generation of the `<command>` section that takes into account the CDATA block has been added. This will include (or omit) the CDATA block in the resulting snippet as needed.
> Fix wrong insert position for auto-generated code snippets

- server/galaxyls/services/completion.py
- server/galaxyls/services/context.py
- server/galaxyls/services/language.py
- server/galaxyls/services/xml/nodes.py
- server/galaxyls/tests/unit/test_completion.py
This should fix #84 and other broken behaviors inside CDATA blocks that were not properly adapted to the new XML parsing system.
> Fix autoclose tags and autocompletion behaviour

- client/src/snippets.json
Some improvements in the `gx-tool` scaffold snippet for creating brand new tools wrappers as suggested by @bgruening:
- Included `macros` section with version (defaults to 0.1.0) and profile tokens.
- Replaced the TODO for licenses by a choice selector with some of the most commonly used licenses (more can be added as convenience).
- Updated some TODO comments for clarity.
Usage example:
This should close #93
> Update gx-tool snippet to latests IUC best practices

- server/galaxyls/server.py
- server/galaxyls/services/validation.py
- server/galaxyls/services/xml/document.py
- server/galaxyls/tests/unit/test_validation.py
Fixes #98 
The old document detection method (to differentiate tool wrappers for other regular XML files) was parsing the whole document using `lxml` just to get the name of the root tag. While `lxml` is extremely performant, this approach has the disadvantage that documents with syntax errors will raise exceptions and so were detected as non-supported documents hence being ignored by the server instead of reporting the actual syntax errors.
The new approach using a 'simple' regular expression should be more robust since we only check for the first tag (root) in a limited chunk at the beginning of the document.
> Improve document root detection method

- server/galaxyls/services/tools/inputs.py
- server/galaxyls/tests/files/nested_conditional_bug_01.xml
- server/galaxyls/tests/files/nested_conditional_bug_01_command.xml
- server/galaxyls/tests/files/nested_conditional_bug_01_test.xml
- server/galaxyls/tests/unit/test_tools.py
When finding the `when` clause associated with a `conditional`, the search was returning multiple possible values instead of the expected in the case of nested conditional with the same `when` value names like:
````xml
<conditional name="parent_conditional">
<param name="option" type="select">
<option value="yes">Yes</option>
<option value="no">No</option>
</param>
<when value="yes">  <---------------------------- This
<conditional name="child_conditional">
<param name="option" type="select">
<option value="yes">Yes</option>
<option value="no">No</option>
</param>
<when value="yes">  <---------------------------- This
<param name="param" type="text"/>
</when>
<when value="no">
</when>
</conditional>
</when>
<when value="no">
</when>
</conditional>
````
> Fix input tree with nested conditional sharing the same 'when' value

- client/package.json
- client/src/commands.ts
If you have the `Galaxy Tools` extension installed, the planemo icon in the left activity bar and all the extension's commands are shown in the command palette even if the extension is not active (i.e. your current workspace or opened folder does not contain any XML tool documents).
This fixes #116 by enabling those views and commands only when the extension has been properly loaded.
> Hide command and view contributions when the extension is not active

- .github/workflows/release.yml
- client/src/constants.ts
- client/src/extension.ts
- client/src/planemo/testing/testAdapter.ts
- client/src/planemo/testing/testRunner.ts
- client/src/setup.ts
- server/setup.py
This will allow setting a specific server version used by a specific client version that doesn't need to match each other.
- The server version is no longer automated and now had to be manually set in each project as part of the release protocol.
- The tag version of the release will now exclusively match the client version.
- The server version will be updated in PyPi only when it changes.
Closes #118
> Detach client and server versions

- .vscode/launch.json
- .vscode/tasks.json
- client/.vscodeignore
- client/package-lock.json
- client/package.json
- client/src/configuration/storage.ts
- client/src/setup.ts
- client/tsconfig.json
- client/webpack.config.js
Some improvements:
- The extension is now bundled using [webpack](https://webpack.js.org/) and should be much lightweight and load faster.
- When installing the extension for the first time, if the default Python version of the system is not supported, a prompt message allows selecting a supported Python interpreter (3.8+). This is not new, the improvement here is that now the interpreter chosen by the user is remembered between extension updates and it doesn't have to be reselected with each new update.
- The language server installation confirmation and the 'Galaxy Tools extension is ready!' notification will be displayed only the first time the extension is installed.
> Improve client installation process

- client/src/planemo/testing/testRunner.ts
- client/src/planemo/testing/testsReportParser.ts
A `{tool_id}_test_report.html` file will be generated for each tool after running the tests from the Test Explorer.
In the output window of each test, a new link to this HTML report file will appear to inspect detailed information about the test results.
Closes #121
> Add link to test html report in the output

- client/package.json
- client/src/commands.ts
- client/src/configuration/galaxyToolWorkspaceConfiguration.ts
- client/src/configuration/workspaceConfiguration.ts
- client/src/planemo/configuration.ts
- client/src/planemo/main.ts
- client/src/planemo/testing/testAdapter.ts
- client/src/planemo/testing/testRunner.ts
- client/src/planemo/views/configurationView.ts
- client/src/planemo/views/main.ts
- client/src/utils.ts
- client/src/views/common.ts
This will display some information about the currently configured `planemo` to be used by the extension. With some considerations:
The so-called `Planemo Explorer` will be the general panel where most of the customs views of the extension will be placed like information about the running state of a `planemo serve` command to name one. Currently, only the planemo configuration view is placed here.
If the planemo configuration is not valid, the previous `Welcome` view will be displayed with some instruction on how to configure it.
After the planemo binary has been set up correctly the `Welcome` view will disappear and the Configuration view will be displayed.
The information about the configuration displayed so far (planemo and galaxy versions, paths, etc.) is just a sample of what may be …
> Planemo Explorer Configuration View

- client/package.json
- client/src/commands.ts
- client/src/constants.ts
- client/src/extension.ts
- client/src/providers/codeActions.ts
- client/src/providers/contentProvider.ts
- client/src/providers/setup.ts
- client/src/utils.ts
- server/galaxyls/constants.py
- server/galaxyls/features.py
- server/galaxyls/server.py
- server/galaxyls/services/completion.py
- server/galaxyls/services/language.py
- server/galaxyls/services/macros.py
- server/galaxyls/services/tools/document.py
- server/galaxyls/services/tools/generators/snippets.py
- server/galaxyls/services/tools/macros.py
- server/galaxyls/services/tools/testing.py
- server/galaxyls/services/validation.py
- server/galaxyls/services/xml/document.py
- server/galaxyls/services/xml/nodes.py
- server/galaxyls/services/xsd/service.py
- server/galaxyls/services/xsd/validation.py
- server/galaxyls/types.py
When a tool document containing macros was validated, the reported errors in the problems tab were a bit 'vague', and a simple 'Validation error on macro...' message was displayed, which wasn't very helpful in determining the exact problem.
This was because the validation was performed in the `expanded` version of the document, so there wasn't an easy way of providing a specific line in the document where the problem was caused as both documents had quite different contents.
To help to identify and locate the real problem when the tool document is not valid after expanding all the macros and tokens, a _new feature_ was introduced that allows **previewing, as a virtual document, the contents of the expanded tool XML**. With this, we can now reference the exact line in the expanded document …
> Improve tool validation troubleshooting with macros

- server/galaxyls/server.py
- server/galaxyls/services/completion.py
- server/galaxyls/services/context.py
- server/galaxyls/services/language.py
- server/galaxyls/services/tools/macros.py
- server/galaxyls/tests/integration/test_completion.py
- server/galaxyls/tests/unit/test_completion.py
- server/galaxyls/tests/unit/test_context.py
xref https://github.com/galaxyproject/galaxy-language-server/issues/44
Now, when you invoke IntelliSense with `ctrl+space` inside a `macro` attribute in `<expand>` elements, the name of your defined macros across your imported files are suggested:
> Auto-complete macro names

- server/galaxyls/services/completion.py
- server/galaxyls/services/tools/macros.py
- server/galaxyls/tests/integration/test_completion.py
xref #44
This allows to auto-complete attributes in `<expand>` elements that reference macros with [dynamic token parameters](https://planemo.readthedocs.io/en/latest/writing_advanced.html#parameterizing-xml-macros-with-tokens).
- The tokens can:
- display their default value on hover.
- navigate to their token parameter definition.
- In the `<expand>` element:
- the attributes will be autocompleted with the name of the token parameter.
- in addition to the attribute name, the default value will be provided as a placeholder for easy edition/reference.
> Support dynamic token parameter attributes in <expand> elements

- server/galaxyls/server.py
- server/galaxyls/services/validation.py
- server/galaxyls/tests/unit/test_validation.py
Empty XML documents were considered invalid, this prevented some features like auto-completion to properly work at the beginning.
Empty XML documents are now considered to be Galaxy tool documents by default until the root element is fully declared.
Also, when an empty document is opened, it won't be validated right away to avoid displaying the `Document is empty` validation error but It will be displayed if you attempt to save it though.
> Fix empty document validation

- server/galaxyls/server.py
This prevents previous existing diagnostics to remain if the document contents are deleted or replaced by a non-galaxy-tool XML document.
> Clear diagnostics when the document is not valid

- client/src/commands.ts
- client/src/providers/contentProvider.ts
- client/src/providers/setup.ts
Fixes #147 
This triggers a `provideTextDocumentContent` every time the `galaxytools.preview.expandedDocument`command is executed which should display the updated expanded document in case there are any changes in the source XML tool document.
> Fix update expand preview

- server/galaxyls/services/xsd/validation.py
Fixes #149 
In addition to the missing offset correction in the location range due to the diagnostics requiring the first line starting at 0, the internal expanded document format was not matching the actual expanded document, so additional empty lines were present in the internal expanded document (the one that gets validated) in comparison with the visible expanded document (which was *pretty-printed*).
> Fix line offset mismatch between diagnostic line and expanded document

- client/src/providers/codeActions.ts
> Fix duplicated CodeActions for the same expand document command

- client/src/configuration/galaxyToolWorkspaceConfiguration.ts
Check for the existence of `<galaxy_root>/lib/galaxy` instead of relying on how the root directory is named.
This should fix https://github.com/galaxyproject/galaxy-language-server/issues/157
Thank you @lldelisle for reporting!
> Fix `planemo.galaxyRoot` parameter validation in Config

- client/README.md
- client/package.json
- client/src/configuration/galaxyToolWorkspaceConfiguration.ts
- client/src/configuration/workspaceConfiguration.ts
- client/src/constants.ts
- client/src/planemo/configuration.ts
- client/src/planemo/testing/testRunner.ts
- client/src/planemo/testing/testsReportParser.ts
This should resolve https://github.com/galaxyproject/galaxy-language-server/issues/161
Instead of adding each `planemo test` argument as a setting in the VSCode extension I just added a single `extraParams` setting that can contain any desired number of arguments. I hope this solution is simple and flexible enough to support most of the use cases.
Also added a console channel called `Planemo Tests` that will display the full command and any error in case the arguments provided caused any trouble whenever the tests are run.
> Add Planemo extra params

- README.md
The gifs and images [are not visible directly from the client readme in GitHub](https://github.com/galaxyproject/galaxy-language-server/blob/master/client/README.md) because of how the resources are referenced from a different branch, so it's probably best to keep them in the main readme too.
> Add the feature list back to main readme

- server/requirements.txt
Apparently, pygls 0.11.2 contains some breaking changes affecting https://github.com/galaxyproject/galaxy-language-server/issues/171.
Reverting to the previous version until we found out the exact issue and fix it.
> Revert pygls to version 0.11.1

- client/src/planemo/testing/main.ts
- client/src/utils.ts
- server/galaxyls/server.py
Fixes #188
Other kinds of documents (even .git documents) were leaking into the test discovery process resulting in errors. Now only valid XML Galaxy tool documents are processed.
> Make sure the current document is a valid Tool document before processing

- client/README.md
- client/src/setup.ts
- client/src/utils.ts
Fixes #195
- Automatically remove the local virtual environment directory `glsenv` when the installation fails. This will try to recreate the full virtual environment on each reload if the server is not installed instead of reusing the broken environment or making the user manually remove it.
- Improve the documentation to make it more obvious that `python3-venv` is a prerequisite.
> Remove local virtual environment when install fails

- client/src/setup.ts
The regex for parsing the Python version was only taking one digit into account for the major and minor version numbers making the `3.8+` requirement fail on Python `3.10+` as it was parsed as `3.1`.
> Fix python version parsing

- server/galaxyls/config.py
- server/galaxyls/server.py
- server/galaxyls/tests/unit/test_config.py
Fixes #219
Apparently, the new `attrs` models (replacing previous pydantic models) in `pygls` cannot work with nested dictionaries on initialization. I probably should have kept using pydantic models, but I wanted to remove the extra dependency so... this should fix it.
> Fix config loading with new attrs classes

- server/galaxyls/config.py
- server/galaxyls/server.py
- server/galaxyls/tests/unit/test_config.py
- server/galaxyls/utils.py
Fixes #223
Use `lsprotocol` converter instead of manually converting from client to server models.
> Simplify and fix model conversion

- client/package-lock.json
- client/package.json
- docs/CONTRIBUTING.md
Following the current instructions, nodejs=18.15.0 gets installed, which results in an error like this:
~/galaxy-language-server/client$ npm run webpack
galaxy-tools@0.10.2 webpack
webpack --mode development
[webpack-cli] /home/tunc/galaxy-language-server/client/node_modules/webpack/lib/cli.js:68
/(\p{Uppercase_Letter}+|\p{Lowercase_Letter}|\d)(\p{Uppercase_Letter}+)/gu,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Invalid regular expression: /(\p{Uppercase_Letter}+|\p{Lowercase_Letter}|\d)(\p{Uppercase_Letter}+)/: Invalid property name
at internalCompileFunction (node:internal/vm:73:18)
at wrapSafe (node:internal/modules/cjs/loader:1176:20)
at Module._compile (node:internal/modules/cjs/loader:1218:27)
at Module._extensions..js …
> Updated dev docs - setup issues

- client/src/snippets.json
I hope this is useful, its needs a careful review. I did this on-the-fly. With example outputs covered, we can actually generate an entire tool just with snippets, which is super useful in demonstrations.
> add a few more snippets

- server/galaxyls/constants.py
- server/galaxyls/server.py
- server/galaxyls/services/completion.py
- server/galaxyls/services/language.py
- server/galaxyls/services/links.py
- server/galaxyls/services/tools/document.py
- server/galaxyls/services/tools/generators/command.py
- server/galaxyls/services/tools/generators/tests.py
- server/galaxyls/services/tools/inputs.py
- server/galaxyls/services/tools/macros.py
- server/galaxyls/services/xml/document.py
- server/galaxyls/services/xml/nodes.py
- server/galaxyls/services/xsd/validation.py
- server/galaxyls/tests/integration/tools/test_document_links.py
Closes #176
In addition to what was already supported to navigate to macro files and definitions, now you can also follow links to your test files.
> Add DocumentLinksProvider and support test-data file links

- client/src/snippets.json
Follow up on #233
The `$` character must be escaped to avoid VSCode confusing "snippet variables" with Galaxy variables.
> Escape $ on non-snippet variables

- client/tests/e2e/suite/extension.e2e.ts
- server/galaxyls/services/xml/document.py
- server/galaxyls/tests/files/validation/tool_02.xml
- server/galaxyls/tests/unit/test_tools.py
Fixes #234
The expanded version of the tool source was only passed to the Galaxy linter when an `expand` tag was present in the unexpanded tool source. This change considers other macro-related tags to ensure the expanded version is linted when necessary.
> Fix macros detection condition

- server/galaxyls/services/completion.py
- server/galaxyls/tests/integration/test_completion.py
Closes #236 
When autocompleting attributes that define a set of valid values, the autocompletion snippet will directly offer a choice dropdown with those values instead of having to manually press `ctrl+space` to trigger the value completion.
> Improve attribute with enum aut-completion

- client/package-lock.json
- client/package.json
- client/src/setup.ts
If there is a more recent version of the GLS already installed, do not downgrade to the old version as the recent version should be compatible and contain additional fixes.
This also plays more nicely with CI end-to-end tests as (since #232) the latest dev version of the LS is installed.
> Relax LS version checking

- server/galaxyls/server.py
- server/galaxyls/services/language.py
- server/galaxyls/services/symbols.py
- server/galaxyls/tests/unit/test_symbols.py
Implements a SymbolProvider for the language server so it can be used to provide a hierarchical view of the document and quickly access elements in the Document Outline.
> Add symbols provider

- client/CHANGELOG.md
- client/README.md
- client/package.json
- client/src/constants.ts
- server/CHANGELOG.md
- server/galaxyls/services/context.py
- server/galaxyls/tests/unit/test_context.py
- server/galaxyls/version.py
- server/requirements.txt
> Release v0.12.0

- client/src/configuration/galaxyToolWorkspaceConfiguration.ts
- client/src/configuration/workspaceConfiguration.ts
- client/src/setup.ts
Adds the option "Don't ask again" when confirming the server installation.
> Add option to skip future server install confirmations

- .github/workflows/client-ci.yml
- README.md
- client/CHANGELOG.md
- client/package-lock.json
- client/package.json
- client/src/constants.ts
- server/CHANGELOG.md
- server/galaxyls/constants.py
- server/galaxyls/server.py
- server/galaxyls/services/tools/document.py
- server/galaxyls/services/tools/generators/command.py
- server/galaxyls/services/tools/generators/snippets.py
- server/galaxyls/services/tools/inputs.py
- server/galaxyls/services/xml/document.py
- server/galaxyls/services/xml/nodes.py
- server/galaxyls/services/xsd/types.py
- server/galaxyls/version.py
- server/requirements-dev.txt
- server/requirements.txt
> Prepare patch 0.12.1

- .github/workflows/client-ci.yml
- .github/workflows/release.yml
- .github/workflows/server-ci.yml
Replace some deprecated GitHub workflow actions with new ones and simplify the release workflow to reuse the same VSIX package.
> Update CI actions

- client/package.json
- client/src/commands.ts
- server/galaxyls/constants.py
- server/galaxyls/server.py
- server/galaxyls/services/language.py
- server/galaxyls/services/references.py
- server/galaxyls/services/tools/document.py
- server/galaxyls/services/tools/generators/snippets.py
- server/galaxyls/services/xml/nodes.py
- server/galaxyls/types.py
fixes #262
This PR adds two new custom commands.
One for picking a `param` reference and then inserting it at the current cursor position. 
And the other one does a similar thing but creates "dictionary access like" references to be used, for example, in output filters.
You can invoke these commands using the Command Palette (ctrl+shift+p) and then searching for Galaxy Tools... or by using the default keyboard shortcuts, `ctrl+alt+i+p` (for insert param reference) and `ctrl+alt+i+f` for inserting the filter version of the reference. Remember that you can always customize your [key bindings](https://code.visualstudio.com/docs/getstarted/keybindings).
> Add feature Insert param reference/output filter

- README.md
- client/CHANGELOG.md
- client/README.md
- client/package-lock.json
- client/package.json
- client/src/constants.ts
- server/CHANGELOG.md
- server/galaxyls/version.py
> Prepare release v0.13.0

- server/galaxyls/services/validation.py
- server/galaxyls/tests/unit/test_validation.py
Reduce false positive detection of other XML files as tool wrappers.
> Fix document detection

- .github/workflows/release.yml
By merging everything into a single release job, we avoid workspace resets, simplify file handling, and ensure everything is executed in the correct order. This should eliminate the ENOENT issue and, hopefully, make the workflow more reliable in future releases.
> Refactor `Release` GitHub Actions workflow

- client/src/setup.ts
This should hopefully help with #270 when using Python 3.12
> Ensure `pip` and `setuptools` are upgraded when creating the virtual environment

- .vscode/launch.json
- client/package.json
- client/src/commands.ts
- client/src/providers/contentProvider.ts
- client/src/providers/setup.ts
- server/galaxyls/constants.py
- server/galaxyls/server.py
- server/galaxyls/services/language.py
- server/galaxyls/services/tools/document.py
- server/galaxyls/services/tools/generators/__init__.py
- server/galaxyls/services/tools/generators/snippets.py
- server/galaxyls/services/tools/generators/tests.py
- server/galaxyls/services/tools/refactor.py
- server/galaxyls/services/xml/document.py
- server/galaxyls/services/xml/nodes.py
- server/galaxyls/tests/files/update_profile_nested_01.xml
- server/galaxyls/tests/files/update_profile_simple_01.xml
- server/galaxyls/tests/unit/sample_data.py
- server/galaxyls/tests/unit/test_tools.py
- server/galaxyls/tests/unit/xml/test_parser.py
- server/galaxyls/types.py
Closes #277 
This pull request adds a new command (by default, the keybinding is `ctrl+alt+u`) to update test cases to the new validation requirement for tool tests introduced in Galaxy 24.2 and planemo.
Suppose we have a tool whose `inputs` section looks as follows:
```xml
<inputs>
<conditional name="c1">
<param name="c1_action" type="select">
<option value="a1" selected="True">A 1</option>
<option value="a2">A 2</option>
</param>
<when value="a1">
<param name="c1_a1_p1" type="text"/>
<repeat name="rep1" title="Sample repeat">
<param name="rep1_p1" type="text"/>
</repeat>
</when>
<when value="a2">
<param name="c1_a2_p1" type="text"/>
<section name="int" title="Integer Section" expanded="true">
<param name="int_test" value="1" type="integer"/>
</section>
</when>
</conditional>
</inputs> …
```
> Add command to upgrade tests to profile 24.2
