server/services/format.py, server/tests/unit/test_format.py
Bug fixed and added some tests for the ``auto-format`` feature.
=> Fix #5 - auto-format on save removes CDATA block

server/services/xsd/constants.py, server/services/xsd/service.py
Replace the ``os`` module to get the XSD file using ``pathlib``.
=> Use ``pathlib`` instead of ``os``

README.md, docs/CHANGELOG.md, docs/CONTRIBUTING.md
Updated the contribution guidelines and the readme to include snippets.
=> Snippets documentation

README.md
This adds a bit more detail to the features listed in the readme.
=> Update features documentation on readme

.github/workflows/main.yml, requirements-dev.txt, server/services/context.py, setup.cfg
Added flake8-bugbear plugin to development dependencies and properly setup [CI Workflow](./.github/workflows/main.yml).
Also fixed the issues reported.
=> Use flake8 bugbear

.vscode/launch.json, README.md, docs/CONTRIBUTING.md, server/CHANGELOG.md, server/README.md, server/setup.py
Prepare setup.py for the language server packaging and some minor updates on documentation.
=> Create package setup

.github/workflows/extension-release.yml, .github/workflows/main.yml, .github/workflows/pypi-release.yml, .vscode/launch.json, README.md, client/package-lock.json, client/package.json, server/setup.py
- Added actions for auto-publish the language server to [PyPI](https://pypi.org/) and the extension to [Open-VSX registry](https://open-vsx.org/).
- Updated the versions of the extension dependencies and removed the ``galleryBanner`` configuration (testing leftovers).
- Minor changes in the general readme.
=> Publish actions

README.md
Updated some instructions after refactoring the project directories.
=> Update getting started instructions

client/package-lock.json, client/package.json, client/src/constants.ts, client/src/setup.ts, server/requirements.txt
- Updated the language server dependencies to latest versions.
- The extension now checks for a specific version of the galaxy-language-server package (the same version as the extension itself).
- Added more logging to troubleshoot the installation process.
=> Update dependencies and version check

.github/workflows/client-cd.yml, README.md, client/CHANGELOG.md, client/package.json, server/CHANGELOG.md, server/README.md
Prepare extension for publishing:
=> Prepare version 0.1.1

README.md
A brief explanation of how to run the server in case someone wants tho run it manually.
This should close #60
=> Add documentation on how to run the server manually

client/CHANGELOG.md, server/CHANGELOG.md
Updated changelogs for the v0.2.1 patch release.
=> Prepare patch v0.2.1

README.md, client/CHANGELOG.md, client/README.md, client/package.json, docs/CONTRIBUTING.md, server/CHANGELOG.md, server/README.md, server/galaxyls/services/language.py, server/requirements.txt
Updated the documentation and the `lxml` dependency.
=> Prepare release 0.3.0

client/package.json, server/requirements.txt
Update the extension version and use the development version of the galaxy-tool-util dependency.
=> Prepare patch 0.3.1

client/CHANGELOG.md, client/package.json, server/CHANGELOG.md
Include fix #100 and updated changelogs.
=> Prepare patch 0.3.2

client/src/commands.ts, server/galaxyls/services/tools/generators/command.py, server/galaxyls/services/tools/generators/snippets.py, server/galaxyls/services/tools/generators/tests.py, server/galaxyls/tests/unit/test_tools.py, server/galaxyls/types.py
=> Display error notification when a code generation command fails

README.md, client/CHANGELOG.md, client/README.md, client/package.json, server/CHANGELOG.md
Updates the documentation before release.
=> Prepare release v0.4.0

.github/workflows/release.yml, client/CHANGELOG.md, client/package.json
=> Prepare patch v0.4.1

server/galaxyls/config.py, server/galaxyls/server.py, server/galaxyls/services/completion.py, server/galaxyls/services/context.py, server/galaxyls/services/format.py, server/galaxyls/services/language.py, server/galaxyls/services/tools/document.py, server/galaxyls/services/tools/generators/command.py, server/galaxyls/services/tools/generators/snippets.py, server/galaxyls/services/tools/generators/tests.py, server/galaxyls/services/xml/document.py, server/galaxyls/services/xml/utils.py, server/galaxyls/services/xsd/service.py, server/galaxyls/services/xsd/types.py, server/galaxyls/services/xsd/validation.py, server/galaxyls/tests/integration/tools/test_iuc.py, server/galaxyls/tests/unit/test_completion.py, server/galaxyls/tests/unit/test_config.py, server/galaxyls/tests/unit/test_context.py, server/galaxyls/tests/unit/test_format.py, server/galaxyls/tests/unit/test_tools.py, server/galaxyls/tests/unit/utils.py, server/galaxyls/tests/unit/xml/test_parser.py, server/galaxyls/tests/unit/xml/test_utils.py, server/galaxyls/types.py, server/requirements.txt
This contains maintenance changes for the language server:
- Bump some server dependencies to the latest version.
- Updating to `pygls==0.10.2` and adapting the server in this commit https://github.com/galaxyproject/galaxy-language-server/commit/eda819e78ef2d3672386adabb50028770fb283b5. See https://github.com/openlawlibrary/pygls/issues/151 for reference.
- Refactor/replace the server configuration class `GalaxyToolsConfiguration` with a pydantic model to benefit from direct parsing and validation.
=> Maintenance changes

server/galaxyls/services/completion.py, server/galaxyls/services/context.py, server/galaxyls/tests/unit/test_context.py
=> Improve completion when manually invoked

client/package-lock.json, client/package.json, client/src/commands.ts, client/src/extension.ts, client/src/planemo/main.ts, client/src/planemo/testing/main.ts, client/src/planemo/views/main.ts, client/src/providers/setup.ts, client/src/tagClosing.ts, client/src/testing/testsProvider.ts
Bump client dependencies to the latest version and adapt the code for `vscode-languageclient` version `7.0.0` which contains some breaking changes.
=> Update client dependencies

server/galaxyls/server.py
=> Clear diagnostics when the file is closed

README.md, client/CHANGELOG.md, client/README.md, client/package.json, client/src/constants.ts, server/CHANGELOG.md, server/README.md, server/requirements.txt, server/setup.py
=> Prepare v0.5.0

README.md, client/README.md
The images were GIFs not PNGs 😅
=> Fix readme image links

client/package-lock.json, client/package.json
Bump development dependencies for the extension. Especially `webpack` and its dependencies.
=> Bump extension dev-dependendies

client/CHANGELOG.md, client/package.json, client/src/constants.ts, server/CHANGELOG.md, server/requirements.txt, server/setup.py
=> Prepare patch v0.5.1

client/CHANGELOG.md, client/package.json, client/src/constants.ts, server/CHANGELOG.md, server/setup.py
=> Prepare patch v0.5.2 release

README.md, client/CHANGELOG.md, client/README.md, client/package-lock.json, client/package.json, client/src/constants.ts, server/CHANGELOG.md, server/galaxyls/services/completion.py, server/requirements.txt, server/setup.py
=> Prepare patch v0.5.3

client/.prettierrc.json, client/package-lock.json, client/package.json, client/src/commands.ts, client/src/configuration/galaxyToolWorkspaceConfiguration.ts, client/src/configuration/storage.ts, client/src/configuration/workspaceConfiguration.ts, client/src/constants.ts, client/src/extension.ts, client/src/planemo/configuration.ts, client/src/planemo/main.ts, client/src/planemo/testing/main.ts, client/src/planemo/testing/testAdapter.ts, client/src/planemo/testing/testRunner.ts, client/src/planemo/testing/testsReportParser.ts, client/src/planemo/views/configurationView.ts, client/src/planemo/views/main.ts, client/src/processRunner.ts, client/src/providers/codeActions.ts, client/src/providers/contentProvider.ts, client/src/providers/setup.ts, client/src/setup.ts, client/src/tagClosing.ts, client/src/testing/common.ts, client/src/testing/testRunner.ts, client/src/testing/testsProvider.ts, client/src/utils.ts, client/src/views/common.ts
This should unify the code style for the client... finally, it's never too late :)
=> Setup Prettier

README.md, client/CHANGELOG.md, client/README.md, client/package-lock.json, client/package.json, client/src/constants.ts, server/CHANGELOG.md, server/requirements.txt, server/setup.py
Sorry for the delay in releasing this :sweat_smile: 
Closes #167
=> Release v0.6.0

.github/workflows/release.yml, .github/workflows/server-ci.yml, README.md, client/src/setup.ts, server/README.md, server/setup.py
=> Rename references to main branch

client/CHANGELOG.md, client/LICENSE, client/package-lock.json, client/package.json, client/src/constants.ts, server/CHANGELOG.md, server/requirements-dev.txt, server/requirements.txt, server/setup.py
=> Release v0.7.0

server/galaxyls/services/language.py, server/galaxyls/services/tools/common.py, server/galaxyls/services/tools/linting.py, server/galaxyls/services/xml/document.py, server/requirements.txt
Closes #180
This PR integrates the full Galaxy linting context with more accurate element detection into the language server thanks to the amazing work by @bernt-matthias in https://github.com/galaxyproject/galaxy/pull/12978.
=> Integrate Galaxy linting

client/tests/e2e/suite/extension.e2e.ts, client/tests/e2e/suite/helpers.ts, client/tests/e2e/suite/index.ts, server/galaxyls/tests/files/validation/tool_01.xml
Add a test for linting and adapt the rest of the tests to take linting into account.
=> Fix e2e tests

client/package.json, client/src/configuration/galaxyToolWorkspaceConfiguration.ts, client/src/configuration/workspaceConfiguration.ts, client/src/extension.ts, client/src/setup.ts
=> Add silent install setting for language server

client/CHANGELOG.md, client/README.md, client/package-lock.json, client/package.json, client/src/constants.ts, server/CHANGELOG.md, server/setup.py
=> Release v0.9.0

.github/workflows/client-ci.yml, .github/workflows/server-ci.yml
Do not run e2e tests on push to the main branch but allow manual triggering.
=> Update GH Workflows

.github/workflows/client-ci.yml, client/package-lock.json, client/package.json, client/src/setup.ts, client/tests/e2e/runTests.ts
- Better error logging
- Fix issue with outdated testing dependency
- Reduce testing matrix for CI
- Always install the latest development version of the language server directly from the source instead of the last published package
=> Improve e2e tests

client/src/snippets.json
And I have not found a new website that does it :(
=> link does not work anymore

client/src/commands.ts
=> Auto-save document before inserting generated snippet

README.md, client/CHANGELOG.md, client/package.json, client/src/constants.ts, server/CHANGELOG.md, server/galaxyls/services/tools/linting.py, server/galaxyls/version.py, server/requirements-dev.txt, server/requirements.txt
=> Prepare release v0.11.0

server/galaxyls/tests/files/validation/tool_02.xml, server/requirements.txt
Is this all what is needed to get the new linting warnings?
=> upgrade dependencies

.github/workflows/client-ci.yml, .github/workflows/release.yml, .github/workflows/server-ci.yml, .vscode/launch.json, client/README.md, client/package-lock.json, client/src/constants.ts, client/src/setup.ts, docs/CONTRIBUTING.md, server/galaxyls/server.py, server/requirements-dev.txt, server/setup.py
This pull request includes updates to Python version support, dropping 3.8, improvements to packaging and dependency management, and adjustments to project metadata as an attempt to keep the building process healthy.
=> Update server build tools + drop Python 3.8
